"""The misconfig linter — ShipMate's "aha" feature.

Each rule inspects a Topology and yields Findings with a severity and a
one-line fix. These are the mistakes that make a first Zerops deploy fail or
behave surprisingly. The rule set is hand-written and fully explainable — this
is the core original logic, not something generated by an LLM.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Callable, List

from .schema import (
    ROLE_API,
    ROLE_DATABASE,
    ROLE_FRONTEND,
    Topology,
)

SEV_ERROR = "error"
SEV_WARN = "warning"
SEV_INFO = "info"


@dataclass
class Finding:
    rule: str
    severity: str
    service: str
    message: str
    fix: str

    def as_dict(self):
        return {
            "rule": self.rule,
            "severity": self.severity,
            "service": self.service,
            "message": self.message,
            "fix": self.fix,
        }


Rule = Callable[[Topology], List[Finding]]
_RULES: List[Rule] = []


def rule(fn: Rule) -> Rule:
    _RULES.append(fn)
    return fn


@rule
def missing_start(topo: Topology) -> List[Finding]:
    out = []
    for s in topo.runtimes():
        if not s.start:
            out.append(Finding(
                "missing-start", SEV_ERROR, s.hostname,
                "Runtime service has no run.start command; the container will never boot.",
                f"Add a run.start to '{s.hostname}', e.g. the command that launches your server.",
            ))
    return out


@rule
def missing_ports(topo: Topology) -> List[Finding]:
    out = []
    for s in topo.runtimes():
        if s.public and not s.ports:
            out.append(Finding(
                "missing-ports", SEV_ERROR, s.hostname,
                "Public service exposes no ports; traffic has nowhere to go.",
                f"Add run.ports with the port your app listens on and httpSupport: true to '{s.hostname}'.",
            ))
    return out


@rule
def http_support_on_public(topo: Topology) -> List[Finding]:
    out = []
    for s in topo.runtimes():
        if s.public:
            for p in s.ports:
                if not p.http_support:
                    out.append(Finding(
                        "http-support", SEV_WARN, s.hostname,
                        f"Public port {p.port} does not set httpSupport; the subdomain won't route HTTP.",
                        f"Set httpSupport: true on port {p.port} of '{s.hostname}'.",
                    ))
    return out


@rule
def localhost_reference(topo: Topology) -> List[Finding]:
    out = []
    for s in topo.runtimes():
        for k, v in s.env.items():
            low = str(v).lower()
            if "localhost" in low or "127.0.0.1" in low or "HOSTNAME" in str(v):
                out.append(Finding(
                    "localhost-ref", SEV_WARN, s.hostname,
                    f"Env var {k} points at localhost; on Zerops services talk over the private network by hostname.",
                    f"Set {k} to the target service's hostname (e.g. 'db' or 'cache'), not localhost.",
                ))
    return out


@rule
def db_referenced_not_declared(topo: Topology) -> List[Finding]:
    out = []
    hostnames = {s.hostname for s in topo.services}
    db_hints = ("DB_HOST", "DATABASE_URL", "POSTGRES_HOST", "PG_HOST", "MONGO_URL")
    has_db = any(s.role == ROLE_DATABASE for s in topo.services)
    for s in topo.runtimes():
        for k, v in s.env.items():
            if k.upper() in db_hints and not has_db:
                out.append(Finding(
                    "db-not-declared", SEV_ERROR, s.hostname,
                    f"{s.hostname} references a database ({k}) but no database service is declared.",
                    "Add a database service (e.g. type postgresql@16) to the import file.",
                ))
                break
    return out


_INTERP_RE = re.compile(r"\$\{[A-Za-z_][A-Za-z0-9_]*")


@rule
def self_referencing_env(topo: Topology) -> List[Finding]:
    """`VAR: ${VAR}` (or any unresolved ${...}) in envVariables — Zerops has no
    outer shell, so it stores the literal placeholder. This is the exact class
    of bug that broke a live deploy: an endpoint env var held the string
    '${AZURE_OPENAI_ENDPOINT}' and the client tried to resolve it as a host."""
    out = []
    for s in topo.runtimes():
        for k, v in s.env.items():
            val = str(v).strip()
            if not _INTERP_RE.search(val):
                continue
            self_ref = re.match(
                r"^\$\{%s(?:[?:}\-]|$)" % re.escape(k), val
            ) or re.match(r"^\$\{%s(?:[?:}\-]|$)" % re.escape(k.upper()), val)
            if self_ref:
                out.append(Finding(
                    "self-ref-env", SEV_WARN, s.hostname,
                    f"Env var {k} references itself (${{{k}}}); on Zerops this stores the "
                    f"literal placeholder, not a value.",
                    f"Remove {k} from envVariables and set it as a GUI env var/secret.",
                ))
            else:
                out.append(Finding(
                    "unresolved-env-interp", SEV_WARN, s.hostname,
                    f"Env var {k} contains an unresolved ${{...}} interpolation; Zerops "
                    f"won't expand it.",
                    f"Set {k} to a literal value, a cross-service hostname, or a GUI secret.",
                ))
    return out


@rule
def public_service_needs_subdomain(topo: Topology) -> List[Finding]:
    out = []
    for s in topo.services:
        if s.role in (ROLE_FRONTEND, ROLE_API) and s.ports and not s.public:
            out.append(Finding(
                "no-subdomain", SEV_WARN, s.hostname,
                f"{s.hostname} exposes ports but subdomain access is off; it won't be reachable publicly.",
                f"Set enableSubdomainAccess: true on '{s.hostname}' in the import file (or route via a domain).",
            ))
    return out


@rule
def hardcoded_secret(topo: Topology) -> List[Finding]:
    secret_keys = ("KEY", "SECRET", "TOKEN", "PASSWORD", "PASS", "APIKEY", "API_KEY")
    out = []
    for s in topo.runtimes():
        for k, v in s.env.items():
            ku = k.upper()
            looks_secret = any(sk in ku for sk in secret_keys)
            is_placeholder = str(v).startswith("${") or v == ""
            if looks_secret and v and not is_placeholder:
                out.append(Finding(
                    "hardcoded-secret", SEV_WARN, s.hostname,
                    f"Env var {k} looks like a secret with a literal value committed in config.",
                    f"Move {k} to envSecrets and reference it as ${{{k}}} instead of hard-coding it.",
                ))
    return out


@rule
def deploy_files_build_output(topo: Topology) -> List[Finding]:
    out = []
    for s in topo.runtimes():
        builds_dist = any("build" in c for c in s.build_commands)
        if builds_dist and s.deploy_files in ("./", ".", ""):
            out.append(Finding(
                "deployfiles-output", SEV_INFO, s.hostname,
                f"{s.hostname} runs a build step but deployFiles ships everything ('./').",
                "Narrow deployFiles to the build output (e.g. dist/, plus runtime deps) for a leaner runtime.",
            ))
    return out


@rule
def ha_for_prod_db(topo: Topology) -> List[Finding]:
    out = []
    for s in topo.services:
        if s.role == ROLE_DATABASE and not s.ha:
            out.append(Finding(
                "db-non-ha", SEV_INFO, s.hostname,
                f"Database '{s.hostname}' is NON_HA (single container); fine for demos, risky for production.",
                f"Consider mode: HA on '{s.hostname}' if the app must survive a node failure.",
            ))
    return out


def lint(topo: Topology) -> List[dict]:
    findings: List[Finding] = []
    for r in _RULES:
        findings.extend(r(topo))
    order = {SEV_ERROR: 0, SEV_WARN: 1, SEV_INFO: 2}
    findings.sort(key=lambda f: order.get(f.severity, 3))
    return [f.as_dict() for f in findings]


def score(findings: List[dict]) -> dict:
    """A 0-10 deploy-readiness score from lint findings. Errors hurt most."""
    errors = sum(1 for f in findings if f["severity"] == SEV_ERROR)
    warnings = sum(1 for f in findings if f["severity"] == SEV_WARN)
    infos = sum(1 for f in findings if f["severity"] == SEV_INFO)
    raw = 10.0 - (errors * 3.0) - (warnings * 1.0) - (infos * 0.25)
    val = max(0, min(10, round(raw)))
    if errors:
        grade = "won't deploy"
    elif warnings:
        grade = "deploys, review"
    else:
        grade = "ship it"
    return {"score": val, "grade": grade, "errors": errors,
            "warnings": warnings, "infos": infos}


def rule_count() -> int:
    return len(_RULES)
